const challenges = [
    "Chanter une chanson a cappella",
    "Faire le coq",
    "Faire dix tours sur soi-même avec un balai",
    "Boire un cocktail préparé par les autres",
    "Faire du pole dance autour d’un lampadaire",
    "Parler sans utiliser une lettre définie",
    "Mimer une célébrité",
    "Faire la vaisselle à la fin de la soirée",
    "Faire la Macarena à l'envers",
    "Interdiction de dire 'non' toute la soirée",
    "Faire un strip-tease (habillé)",
    "Parler en chantant",
    "Faire un tweet embarrassant",
    "Raconter une blague sans rire",
    "Imiter la démarche de la personne à votre droite",
    "Faire un selfie dans une position ridicule",
    "Échanger vos vêtements avec une autre personne",
    "Faire un discours comme si vous étiez président",
    "Tenir un œuf sur une cuillère et faire le tour de la pièce",
    "Danser comme si personne ne regardait",
    "Faire un moonwalk",
    "Imiter un animal",
    "Chanter une chanson à l'envers",
    "Danser sur une chanson choisie",
    "Mimer un film",
    "Échanger son verre avec la personne en face",
    "Faire le poirier",
    "Parler avec un accent",
    "Faire une danse TikTok",
    "Envoyer un message embarrassant à un ex",
    "Changer la sonnerie de ton téléphone pour un son ridicule",
    "Dire une phrase en chuchotant dans l’oreille d’un autre joueur",
    "Imiter un bébé qui pleure",
    "Porter une chaussette sur une main pendant deux tours",
    "Faire 10 pompes ou squats",
    "Faire un tour de la pièce en courant sur les genoux",
    "Appeler un restaurant et poser une question ridicule",
    "Parler en rimes pendant 5 minutes",
    "Dessiner quelque chose les yeux fermés",
    "Mettre un glaçon dans son pantalon",
    "Inventer une chanson de rap sur un sujet aléatoire",
    "Faire semblant de rire de manière excessive à tout ce qui est dit",
    "Dire un tongue twister trois fois rapidement",
    "Faire une déclaration d'amour à un inconnu sur les réseaux sociaux",
    "Faire une grimace pour le reste du tour",
    "Changer de voix à chaque phrase pendant 2 minutes",
    "Dessiner une moustache sur ton visage avec un marqueur",
    "Imiter un robot cassé",
    "Faire un cri d'animal chaque fois que quelqu'un dit ton prénom",
    "Prendre un selfie embarrassant et le poster en story",
    "Manger un citron sans faire de grimace",
    "Faire semblant d'être en slow motion pendant 2 minutes",
    "Imiter une publicité à la télé",
    "Porter des lunettes de soleil à l’intérieur jusqu’à la fin du tour",
    "Écrire un poème en 1 minute",
    "Essayer de toucher ton nez avec ta langue",
    "Faire semblant de parler une langue étrangère",
    "Porter une chaussette sur la tête pendant 3 minutes",
    "Changer de prénom pour le reste de la soirée",
    "Dire un mot interdit",
    "Manger un piment",
    "Faire un câlin à chaque personne dans la pièce",
    "Imiter un prof que vous avez tous eu",
    "Faire semblant d'être dans un film d'action",
    "Inventer une danse avec un partenaire",
    "Boire un verre sans utiliser les mains",
    "Raconter une histoire effrayante en moins de 2 minutes",
    "Faire 10 sauts en l’air",
    "Mimer une scène de film célèbre",
    "Faire un striptease avec des vêtements imaginaires",
    "Appeler un ami et lui chanter 'Joyeux Anniversaire' sans raison",
    "Porter un accessoire ridicule jusqu'à la fin du tour",
    "Faire un bisou sur la main d’un autre joueur",
    "Faire semblant d’être un serveur pendant 5 minutes",
    "Dire 'oui chef' à tout ce que l’on te dit pendant 10 minutes",
    "Imiter un instrument de musique",
    "Lire une page d’un livre ou d’un journal à l’envers",
    "Faire une déclaration dramatique d’un film",
    "Faire du breakdance",
    "Chanter une chanson en faisant des gestes",
    "Complimenter quelqu'un",
    "Réciter l'alphabet à l'envers",
    "Faire un défi de danse",
    "Imiter la personne à votre droite",
    "Faire une roulade",
    "Parler en rimes",
    "Défi du gobelet",
    "Faire du breakdance",
    "Mimer la personne à ma droite",
    "Boire son verre en entier",
    "Échanger son verre avec la personne en face",
    "Chanter une chanson de Disney",
    "Faire un poirier pendant 10 secondes",
    "Faire un strip-tease (sans enlever de vêtements)",
    "Imiter un accent étranger",
    "Faire un concours de grimaces",
    "Danser comme une poule",
    "Faire un discours de mariage",
    "Boire un shot cul sec",
    "Faire un concours de hula hoop",
    "Faire un concours de twerk",
    "Faire un concours de rap",
    "Faire un concours de karaoké",
    "Danser comme un robot",
    "Faire un compliment original à chaque personne",
    "Inverser les vêtements avec une autre personne",
    "Boire à l'envers",
    "Dire l'alphabet à l'envers",
    "Changer de place avec la personne en face",
    "Faire un bisou à la personne de ton choix",
    "Parler avec un accent",
    "Tenir en équilibre sur une jambe",
    "Faire un selfie de groupe",
    "Raconter un secret",
    "Écrire un mot sur le front de quelqu'un",
    "Chanter une chanson en remplaçant les mots par 'la la la'",
    "Manger un aliment bizarre",
    "Lancer un défi à quelqu'un d'autre",
    "Jouer à pierre-feuille-ciseaux",
    "Déclarer son amour à un objet"
    "Chanter une chanson a cappella",
    "Faire le coq",
    "Faire dix tours sur soi-même avec un balai",
    "Boire un cocktail préparé par les autres",
    "Faire du pole dance autour d’un lampadaire",
    "Parler sans utiliser une lettre définie",
    "Mimer une célébrité",
    "Faire la vaisselle à la fin de la soirée",
    "Faire la Macarena à l'envers",
    "Interdiction de dire 'non' toute la soirée",
    "Faire un strip-tease (habillé)",
    "Parler en chantant",
    "Faire un tweet embarrassant",
    "Raconter une blague sans rire",
    "Imiter la démarche de la personne à votre droite",
    "Faire un selfie dans une position ridicule",
    "Échanger vos vêtements avec une autre personne",
    "Faire un discours comme si vous étiez président",
    "Tenir un œuf sur une cuillère et faire le tour de la pièce",
    "Danser comme si personne ne regardait",
    // Défis axés sur Hiro
    "Hiro doit faire un moonwalk après avoir bu un shot",
    "Hiro doit imiter un animal après avoir pris une bouffée d'herbe",
    "Hiro doit chanter une chanson à l'envers après un verre de vin",
    "Hiro doit danser sur une chanson choisie par le groupe après avoir fumé",
    "Hiro doit mimer un film en ayant les yeux bandés",
    "Hiro doit échanger son verre avec la personne en face et boire cul sec",
    "Hiro doit raconter une blague en tenant un glaçon dans sa bouche",
    "Hiro doit faire le poirier après avoir bu un cocktail",
    "Hiro doit parler avec un accent après avoir fumé",
    "Hiro doit faire une danse TikTok après un verre de bière",
    "Hiro doit envoyer un message embarrassant à un ex après un shot",
    "Hiro doit changer la sonnerie de son téléphone pour un son ridicule",
    "Hiro doit dire une phrase en chuchotant dans l’oreille d’un autre joueur",
    "Hiro doit imiter un bébé qui pleure après avoir bu un verre",
    "Hiro doit porter une chaussette sur une main pendant deux tours",
    "Hiro doit faire 10 pompes ou squats après avoir fumé",
    "Hiro doit faire un tour de la pièce en courant sur les genoux",
    "Hiro doit appeler un restaurant et poser une question ridicule",
    "Hiro doit parler en rimes pendant 5 minutes après un shot",
    "Hiro doit dessiner quelque chose les yeux fermés après avoir fumé"
];

let challengeCount = 0;

function displayRandomChallenge() {
    if (challengeCount < 20) {
        const randomIndex = Math.floor(Math.random() * challenges.length);
        document.getElementById('challenge-display').textContent = challenges[randomIndex];
        challengeCount++;
        document.getElementById('challenge-counter').textContent = `${challengeCount}/20`;
        document.getElementById('progress').style.width = `${(challengeCount / 20) * 100}%`;
    }
    if (challengeCount === 20) {
        document.getElementById('new-challenge-btn').style.display = 'none';
        const replayBtn = document.getElementById('replay-btn');
        replayBtn.style.display = 'inline-block';
        replayBtn.classList.add('large');
    }
}

document.getElementById('new-challenge-btn').addEventListener('click', displayRandomChallenge);

document.getElementById('replay-btn').addEventListener('click', () => {
    challengeCount = 0;
    document.getElementById('new-challenge-btn').style.display = 'inline-block';
    document.getElementById('replay-btn').style.display = 'none';
    document.getElementById('replay-btn').classList.remove('large');
    document.getElementById('challenge-display').textContent = "Cliquez sur le bouton pour un défi !";
    document.getElementById('challenge-counter').textContent = "0/20";
    document.getElementById('progress').style.width = "0%";
});